const urduDictionary: Record<string, string> = {
  the: "یہ",
  this: "یہ",
  is: "ہے",
  a: "ایک",
  an: "ایک",
  of: "کا",
  in: "میں",
  and: "اور",
  to: "کو",
  with: "کے ساتھ",
  for: "کے لئے",
  from: "سے",
  that: "جو",
  by: "کے ذریعے",
  on: "پر",
  it: "یہ",
  as: "بطور",
  be: "ہونا",
  are: "ہیں",
  was: "تھا",
  were: "تھے",
  will: "ہوگا",
  can: "سکتا ہے",
  should: "چاہئے",
  blog: "بلاگ",
  article: "مضمون",
  content: "مواد",
  read: "پڑھیں",
  write: "لکھیں",
  programming: "پروگرامنگ",
  development: "ترقی",
  code: "کوڈ",
  developer: "ڈویلپر",
  website: "ویب سائٹ",
  technology: "ٹیکنالوجی",
  tutorial: "سبق",
  language: "زبان",
  function: "فنکشن",
  app: "ایپ",
  application: "درخواست",
  summary: "خلاصہ",
  introduction: "تعارف",
  paragraph: "پیراگراف",
  learn: "سیکھیں",
  important: "اہم",
  performance: "کارکردگی",
  best: "بہترین",
  practice: "عمل",
  useful: "مفید",
  tips: "مشورے",
  tricks: "چالیں",
  fast: "تیز",
  slow: "سست",
  good: "اچھا",
  bad: "برا",
  success: "کامیابی",
  error: "خرابی",
  solution: "حل",
  testing: "جانچ",
  update: "تازہ کاری",
  improve: "بہتر بنائیں",
  user: "صارف",
  interface: "انٹرفیس",
  design: "ڈیزائن",
  system: "نظام",
  data: "ڈیٹا",
  database: "ڈیٹابیس",
  server: "سرور",
  client: "کلائنٹ",
  backend: "بیک اینڈ",
  frontend: "فرنٹ اینڈ",
  open: "کھولیں",
  close: "بند کریں",
  click: "کلک",
  enter: "درج کریں",
  name: "نام",
  description: "تفصیل",
  link: "لنک",
  internet: "انٹرنیٹ",
  online: "آن لائن",
  offline: "آف لائن",
  connection: "کنکشن",
  secure: "محفوظ",
  password: "پاس ورڈ",
  email: "ای میل",
  message: "پیغام",
  download: "ڈاؤن لوڈ",
  upload: "اپ لوڈ",
};

export function translateToUrdu(text: string): string {
  return text
    .split(/\s+/)
    .map((word) => {
      // Remove surrounding punctuation
      const cleanWord = word.toLowerCase().replace(/[^a-zA-Z]/g, '');
      const urdu = urduDictionary[cleanWord];
      return urdu ? urdu : word;
    })
    .join(' ');
}
