const urduDict: Record<string, string> = {
  hello: "سلام",
  world: "دنیا",
  blog: "بلاگ",
  this: "یہ",
  is: "ہے",
  a: "ایک",
  summary: "خلاصہ",
  ethics: "اخلاقیات",
  developer: "ڈویلپر",
  programming: "پروگرامنگ",
  responsibility: "ذمہ داری",
  practices: "طرز عمل",
  good: "اچھے",
  bad: "برے",
  code: "کوڈ",
  software: "سافٹ ویئر",
  design: "ڈیزائن",
  function: "فنکشن",
  logic: "منطق",
  interface: "انٹرفیس",
  development: "ترقی",
  project: "منصوبہ",
  team: "ٹیم",
  performance: "کارکردگی",
  bug: "نقص",
  error: "غلطی",
  fix: "درست کرنا",
  test: "ٹیسٹ",
  testing: "ٹیسٹنگ",
  agile: "ایجائل",
  scrum: "سکرم",
  task: "کام",
  report: "رپورٹ",
  user: "صارف",
  experience: "تجربہ",
  security: "سیکیورٹی",
  privacy: "پرائیویسی",
  internet: "انٹرنیٹ",
  network: "نیٹ ورک",
  data: "ڈیٹا",
  database: "ڈیٹا بیس",
  system: "سسٹم",
  server: "سرور",
  client: "کلائنٹ",
  request: "درخواست",
  response: "جواب",
  api: "اے پی آئی",
  frontend: "فرنٹ اینڈ",
  backend: "بیک اینڈ",
  fullstack: "فل اسٹیک",
  language: "زبان",
  script: "سکرپٹ",
  variable: "ویری ایبل",
  constant: "کونسٹنٹ",
  array: "ارے",
  object: "آبجیکٹ",
  class: "کلاس",
  method: "طریقہ",
  loop: "لوپ",
  condition: "شرط",
  value: "قدر",
  input: "ان پٹ",
  output: "آؤٹ پٹ",
  return: "واپسی",
  warning: "انتباہ",
  success: "کامیابی",
  failure: "ناکامی",
  load: "لوڈ",
  fetch: "حاصل کریں",
  read: "پڑھیں",
  write: "لکھیں",
  update: "اپ ڈیٹ",
  delete: "حذف کریں",
  create: "بنائیں",
  build: "تعمیر کریں",
  deploy: "تعینات کریں",
  upload: "اپ لوڈ",
  download: "ڈاؤن لوڈ",
  install: "انسٹال کریں",
  uninstall: "ان انسٹال کریں",
  login: "لاگ ان کریں",
  logout: "لاگ آؤٹ کریں",
  signup: "سائن اپ کریں",
  signin: "سائن ان کریں",
  dashboard: "ڈیش بورڈ",
  settings: "ترتیبات",
  profile: "پروفائل",
  account: "اکاؤنٹ",
  admin: "ایڈمن",
  guest: "مہمان",
  member: "رکن",
  student: "طالب علم",
  teacher: "استاد",
  page: "صفحہ",
  content: "مواد",
  article: "مضمون",
  post: "پوسٹ",
  comment: "تبصرہ",
  like: "پسند کریں",
  share: "شیئر کریں",
  follow: "فالو کریں",
  unfollow: "ان فالو کریں",
  message: "پیغام",
  notification: "اطلاع",
  alert: "الرٹ"
};

export function translateToUrdu(text: string): string {
  return text.split(' ').map(word => {
    const cleaned = word.toLowerCase().replace(/[^a-z]/g, '');
    return urduDict[cleaned] || word;
  }).join(' ');
}
